<?php

namespace App\Support;

use App\Enums\UserRole;

class PermissionMatrix
{
    public static function permissions(): array
    {
        return [
            'dashboard.view',
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'roles.manage',
            'settings.view',
            'settings.update',
            'products.view',
            'products.create',
            'products.update',
            'products.delete',
            'stock.adjust',
            'customers.view',
            'customers.create',
            'customers.update',
            'customers.delete',
            'suppliers.view',
            'suppliers.create',
            'suppliers.update',
            'suppliers.delete',
            'sales.view',
            'sales.create',
            'sales.update',
            'sales.cancel',
            'sales.complete',
            'invoices.view',
            'invoices.download',
            'payments.record',
            'purchases.view',
            'purchases.create',
            'purchases.update',
            'cash_transactions.view',
            'cash_transactions.create',
            'cash_transactions.update',
            'cash_transactions.delete',
            'documents.view',
            'documents.create',
            'documents.update',
            'documents.delete',
            'reports.view',
            'audit_logs.view',
            'tags.manage',
        ];
    }

    public static function roles(): array
    {
        return array_map(static fn (UserRole $role) => $role->value, UserRole::cases());
    }

    public static function permissionsForRole(UserRole $role): array
    {
        return match ($role) {
            UserRole::Owner => self::permissions(),
            UserRole::Manager => [
                'dashboard.view',
                'users.view',
                'users.create',
                'users.update',
                'products.view',
                'products.create',
                'products.update',
                'stock.adjust',
                'customers.view',
                'customers.create',
                'customers.update',
                'suppliers.view',
                'suppliers.create',
                'suppliers.update',
                'sales.view',
                'sales.create',
                'sales.update',
                'sales.cancel',
                'sales.complete',
                'invoices.view',
                'invoices.download',
                'payments.record',
                'purchases.view',
                'purchases.create',
                'purchases.update',
                'cash_transactions.view',
                'cash_transactions.create',
                'cash_transactions.update',
                'documents.view',
                'documents.create',
                'documents.update',
                'reports.view',
                'audit_logs.view',
                'tags.manage',
                'settings.view',
            ],
            UserRole::Cashier => [
                'dashboard.view',
                'customers.view',
                'sales.view',
                'invoices.view',
                'invoices.download',
                'payments.record',
                'cash_transactions.view',
                'cash_transactions.create',
                'cash_transactions.update',
                'reports.view',
                'documents.view',
                'documents.create',
            ],
            UserRole::SalesStaff => [
                'dashboard.view',
                'products.view',
                'customers.view',
                'customers.create',
                'customers.update',
                'sales.view',
                'sales.create',
                'sales.update',
                'invoices.view',
                'documents.view',
                'documents.create',
            ],
            UserRole::Storekeeper => [
                'dashboard.view',
                'products.view',
                'products.create',
                'products.update',
                'stock.adjust',
                'suppliers.view',
                'suppliers.create',
                'suppliers.update',
                'purchases.view',
                'purchases.create',
                'purchases.update',
                'documents.view',
                'documents.create',
                'reports.view',
            ],
            UserRole::Viewer => [
                'dashboard.view',
                'products.view',
                'customers.view',
                'suppliers.view',
                'sales.view',
                'invoices.view',
                'purchases.view',
                'cash_transactions.view',
                'documents.view',
                'reports.view',
                'audit_logs.view',
            ],
        };
    }
}
